// Wild Rift Counter Pick Data
// roles: baron=top, jungle, mid, duo=adc, support
// counters: sorted by effectiveness, each entry: [championKey, primaryRole]
// primaryRole indicates the lane the counter is most effective from
// Updated for Patch 7.0 (2026)

const CHAMPIONS = {
  aatrox: { name: "Aatrox", roles: ["baron", "mid"], counters: ["fiora","vayne","kennen","teemo","jayce","quinn","cassiopeia","malphite","singed","garen"] },
  ahri: { name: "Ahri", roles: ["mid"], counters: ["kassadin","yasuo","fizz","zed","katarina","malphite","diana","vex","renekton","annie"] },
  akali: { name: "Akali", roles: ["mid", "baron"], counters: ["galio","annie","malzahar","kassadin","renekton","pantheon","mordekaiser","lissandra","heimerdinger","syndra"] },
  akshan: { name: "Akshan", roles: ["mid", "baron"], counters: ["zed","fizz","irelia","yasuo","diana","syndra","ahri","lux","ziggs","orianna"] },
  alistar: { name: "Alistar", roles: ["support"], counters: ["morgana","janna","soraka","zyra","braum","thresh","nami","lulu","karma","senna"] },
  ambessa: { name: "Ambessa", roles: ["baron", "jungle"], counters: ["malphite","teemo","vayne","kennen","garen","fiora","renekton","ornn","singed","poppy"] },
  amumu: { name: "Amumu", roles: ["jungle", "support"], counters: ["morgana","shyvana","master-yi","olaf","kayn","graves","lee-sin","kindred","kha-zix","rengar"] },
  annie: { name: "Annie", roles: ["mid", "support"], counters: ["syndra","lux","ziggs","xerath","vel-koz","brand","ahri","orianna","kassadin","fizz"] },
  ashe: { name: "Ashe", roles: ["duo", "support"], counters: ["samira","draven","lucian","kai-sa","vayne","tristana","sivir","jinx","miss-fortune","ezreal"] },
  "aurelion-sol": { name: "Aurelion Sol", roles: ["mid"], counters: ["kassadin","fizz","zed","yasuo","katarina","malphite","irelia","renekton","talon","garen"] },
  aurora: { name: "Aurora", roles: ["mid", "baron"], counters: ["kassadin","galio","syndra","orianna","lux","ahri","vex","annie","malzahar","brand"] },
  bard: { name: "Bard", roles: ["support"], counters: ["leona","nautilus","thresh","blitzcrank","alistar","pyke","zyra","brand","morgana","lux"] },
  blitzcrank: { name: "Blitzcrank", roles: ["support"], counters: ["morgana","sivir","ezreal","alistar","leona","braum","thresh","nautilus","lulu","janna"] },
  brand: { name: "Brand", roles: ["mid", "support"], counters: ["fizz","zed","yasuo","kassadin","galio","diana","irelia","katarina","ekko","akali"] },
  braum: { name: "Braum", roles: ["support"], counters: ["morgana","zyra","brand","vel-koz","senna","karma","soraka","nami","janna","lulu"] },
  caitlyn: { name: "Caitlyn", roles: ["duo"], counters: ["samira","draven","lucian","vayne","kai-sa","sivir","tristana","jinx","xayah","ezreal"] },
  camille: { name: "Camille", roles: ["baron", "jungle"], counters: ["jax","fiora","renekton","darius","mordekaiser","malphite","poppy","shen","akali","irelia"] },
  corki: { name: "Corki", roles: ["mid"], counters: ["kassadin","yasuo","zed","fizz","irelia","malphite","syndra","renekton","diana","katarina"] },
  darius: { name: "Darius", roles: ["baron"], counters: ["vayne","kennen","teemo","jayce","kayle","quinn","gnar","fiora","renekton","malphite"] },
  diana: { name: "Diana", roles: ["mid", "jungle"], counters: ["kassadin","galio","malzahar","mordekaiser","lissandra","annie","syndra","orianna","heimerdinger","brand"] },
  "dr-mundo": { name: "Dr. Mundo", roles: ["baron", "jungle"], counters: ["fiora","vayne","gwen","mordekaiser","darius","kayle","tryndamere","camille","gnar","sett"] },
  draven: { name: "Draven", roles: ["duo"], counters: ["caitlyn","ezreal","tristana","kai-sa","vayne","jinx","sivir","ashe","xayah","lucian"] },
  ekko: { name: "Ekko", roles: ["mid", "jungle"], counters: ["kassadin","galio","malzahar","annie","diana","syndra","lissandra","mordekaiser","pantheon","orianna"] },
  evelynn: { name: "Evelynn", roles: ["jungle"], counters: ["lee-sin","rengar","kha-zix","graves","olaf","warwick","vi","xin-zhao","jarvan-iv","nocturne"] },
  ezreal: { name: "Ezreal", roles: ["duo"], counters: ["draven","lucian","samira","kai-sa","vayne","tristana","sivir","caitlyn","jinx","miss-fortune"] },
  fiddlesticks: { name: "Fiddlesticks", roles: ["jungle", "support"], counters: ["lee-sin","olaf","graves","xin-zhao","rengar","kha-zix","nocturne","vi","warwick","jarvan-iv"] },
  fiora: { name: "Fiora", roles: ["baron"], counters: ["malphite","singed","kennen","teemo","vayne","quinn","pantheon","renekton","poppy","gnar"] },
  fizz: { name: "Fizz", roles: ["mid"], counters: ["galio","malzahar","lissandra","annie","kassadin","diana","pantheon","mordekaiser","syndra","orianna"] },
  galio: { name: "Galio", roles: ["mid", "support"], counters: ["fiora","vayne","camille","gwen","mordekaiser","kassadin","kayle","darius","tryndamere","yasuo"] },
  garen: { name: "Garen", roles: ["baron", "mid"], counters: ["vayne","teemo","kennen","jayce","kayle","quinn","gnar","darius","camille","fiora"] },
  gnar: { name: "Gnar", roles: ["baron"], counters: ["irelia","yasuo","camille","fiora","riven","jax","tryndamere","darius","renekton","gwen"] },
  gragas: { name: "Gragas", roles: ["jungle", "baron", "support"], counters: ["lee-sin","olaf","graves","kha-zix","rengar","vi","xin-zhao","nocturne","jarvan-iv","warwick"] },
  graves: { name: "Graves", roles: ["jungle"], counters: ["rammus","amumu","vi","warwick","lee-sin","xin-zhao","olaf","jarvan-iv","nocturne","kha-zix"] },
  gwen: { name: "Gwen", roles: ["baron"], counters: ["kennen","vayne","teemo","jayce","quinn","malphite","darius","renekton","irelia","fiora"] },
  hecarim: { name: "Hecarim", roles: ["jungle"], counters: ["rammus","amumu","lee-sin","olaf","warwick","vi","xin-zhao","graves","jarvan-iv","nocturne"] },
  heimerdinger: { name: "Heimerdinger", roles: ["mid", "baron", "support"], counters: ["syndra","xerath","ziggs","vel-koz","zed","fizz","yasuo","irelia","kassadin","brand"] },
  irelia: { name: "Irelia", roles: ["mid", "baron"], counters: ["malphite","renekton","sett","volibear","tryndamere","garen","jax","fiora","poppy","mordekaiser"] },
  janna: { name: "Janna", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","senna","karma"] },
  "jarvan-iv": { name: "Jarvan IV", roles: ["jungle", "baron"], counters: ["lee-sin","olaf","graves","vi","xin-zhao","warwick","kha-zix","rengar","amumu","nocturne"] },
  jax: { name: "Jax", roles: ["baron", "jungle"], counters: ["malphite","kennen","teemo","jayce","gnar","vayne","quinn","singed","akali","fiora"] },
  jayce: { name: "Jayce", roles: ["baron", "mid"], counters: ["irelia","malphite","camille","fiora","wukong","riven","yasuo","jax","renekton","darius"] },
  jhin: { name: "Jhin", roles: ["duo"], counters: ["samira","draven","lucian","kai-sa","vayne","tristana","sivir","caitlyn","ezreal","jinx"] },
  jinx: { name: "Jinx", roles: ["duo"], counters: ["draven","lucian","samira","kai-sa","vayne","tristana","caitlyn","sivir","ezreal","ashe"] },
  "k-sante": { name: "K'Sante", roles: ["baron"], counters: ["fiora","vayne","gwen","mordekaiser","darius","kayle","camille","irelia","gnar","tryndamere"] },
  "kai-sa": { name: "Kai'Sa", roles: ["duo"], counters: ["draven","caitlyn","lucian","sivir","ashe","tristana","jinx","miss-fortune","ezreal","samira"] },
  kalista: { name: "Kalista", roles: ["duo"], counters: ["ashe","caitlyn","jinx","sivir","tristana","miss-fortune","draven","lucian","vayne","ezreal"] },
  karma: { name: "Karma", roles: ["support", "mid"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","soraka","nami"] },
  kassadin: { name: "Kassadin", roles: ["mid"], counters: ["zed","talon","pantheon","renekton","lucian","jayce","tristana","quinn","irelia","yasuo"] },
  katarina: { name: "Katarina", roles: ["mid"], counters: ["galio","kassadin","diana","malzahar","annie","pantheon","fizz","syndra","lissandra","sett"] },
  kayle: { name: "Kayle", roles: ["baron", "mid"], counters: ["pantheon","renekton","irelia","camille","riven","darius","jax","tryndamere","fiora","yasuo"] },
  kayn: { name: "Kayn", roles: ["jungle"], counters: ["lee-sin","olaf","graves","warwick","vi","xin-zhao","kha-zix","rengar","rammus","amumu"] },
  kennen: { name: "Kennen", roles: ["baron"], counters: ["irelia","yasuo","camille","fiora","riven","jax","gwen","sylas","akali","diana"] },
  "kha-zix": { name: "Kha'Zix", roles: ["jungle"], counters: ["rammus","lee-sin","olaf","warwick","vi","xin-zhao","graves","amumu","rengar","nocturne"] },
  kindred: { name: "Kindred", roles: ["jungle"], counters: ["lee-sin","olaf","graves","vi","xin-zhao","warwick","kha-zix","rengar","rammus","amumu"] },
  "kog-maw": { name: "Kog'Maw", roles: ["duo"], counters: ["draven","lucian","samira","kai-sa","vayne","tristana","caitlyn","sivir","ezreal","jinx"] },
  "lee-sin": { name: "Lee Sin", roles: ["jungle"], counters: ["rammus","amumu","olaf","warwick","vi","graves","xin-zhao","nocturne","jarvan-iv","shyvana"] },
  leona: { name: "Leona", roles: ["support"], counters: ["morgana","janna","soraka","braum","alistar","thresh","zyra","nami","lulu","karma"] },
  lillia: { name: "Lillia", roles: ["jungle", "baron"], counters: ["lee-sin","olaf","graves","vi","xin-zhao","kha-zix","rengar","warwick","nocturne","jarvan-iv"] },
  lissandra: { name: "Lissandra", roles: ["mid"], counters: ["kassadin","syndra","malphite","orianna","ahri","vel-koz","sett","ziggs","renekton","lux"] },
  lucian: { name: "Lucian", roles: ["duo", "mid"], counters: ["vayne","kai-sa","jinx","sivir","caitlyn","tristana","draven","ezreal","ashe","samira"] },
  lulu: { name: "Lulu", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","zyra","brand","senna","pyke","morgana"] },
  lux: { name: "Lux", roles: ["mid", "support"], counters: ["fizz","zed","yasuo","kassadin","irelia","katarina","diana","akali","talon","ekko"] },
  malphite: { name: "Malphite", roles: ["baron", "support"], counters: ["gwen","mordekaiser","fiora","vayne","kayle","darius","tryndamere","camille","nasus","dr-mundo"] },
  maokai: { name: "Maokai", roles: ["support", "baron", "jungle"], counters: ["morgana","zyra","brand","vel-koz","senna","karma","soraka","nami","lulu","janna"] },
  "master-yi": { name: "Master Yi", roles: ["jungle"], counters: ["rammus","jax","amumu","lee-sin","warwick","vi","xin-zhao","olaf","graves","nocturne"] },
  mel: { name: "Mel", roles: ["mid", "support"], counters: ["fizz","zed","kassadin","yasuo","katarina","diana","irelia","akali","talon","ekko"] },
  milio: { name: "Milio", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","senna","morgana"] },
  "miss-fortune": { name: "Miss Fortune", roles: ["duo"], counters: ["draven","lucian","samira","kai-sa","vayne","tristana","caitlyn","sivir","ezreal","jinx"] },
  mordekaiser: { name: "Mordekaiser", roles: ["baron"], counters: ["fiora","vayne","gwen","kayle","tryndamere","darius","gnar","kennen","teemo","jayce"] },
  morgana: { name: "Morgana", roles: ["support", "mid"], counters: ["zyra","brand","vel-koz","xerath","senna","karma","soraka","nami","lulu","janna"] },
  nami: { name: "Nami", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","senna","morgana"] },
  nasus: { name: "Nasus", roles: ["baron"], counters: ["vayne","teemo","gwen","darius","gnar","kennen","jayce","kayle","fiora","quinn"] },
  nautilus: { name: "Nautilus", roles: ["support"], counters: ["morgana","janna","soraka","braum","alistar","thresh","zyra","nami","lulu","karma"] },
  nidalee: { name: "Nidalee", roles: ["jungle"], counters: ["lee-sin","olaf","graves","vi","xin-zhao","warwick","kha-zix","rengar","rammus","amumu"] },
  nilah: { name: "Nilah", roles: ["duo"], counters: ["caitlyn","ashe","jinx","draven","lucian","sivir","tristana","miss-fortune","kai-sa","ezreal"] },
  nocturne: { name: "Nocturne", roles: ["jungle"], counters: ["rammus","lee-sin","olaf","warwick","vi","amumu","xin-zhao","graves","jarvan-iv","rengar"] },
  norra: { name: "Norra", roles: ["mid", "support"], counters: ["fizz","zed","kassadin","yasuo","diana","irelia","katarina","akali","talon","ekko"] },
  "nunu-willump": { name: "Nunu & Willump", roles: ["jungle"], counters: ["olaf","lee-sin","graves","kha-zix","kindred","vi","xin-zhao","warwick","rengar","nocturne"] },
  olaf: { name: "Olaf", roles: ["jungle", "baron"], counters: ["vayne","graves","kha-zix","lee-sin","vi","kindred","xin-zhao","warwick","rengar","amumu"] },
  orianna: { name: "Orianna", roles: ["mid"], counters: ["fizz","zed","kassadin","yasuo","katarina","malphite","irelia","renekton","diana","akali"] },
  ornn: { name: "Ornn", roles: ["baron"], counters: ["fiora","vayne","gwen","mordekaiser","darius","kayle","tryndamere","camille","gnar","kennen"] },
  pantheon: { name: "Pantheon", roles: ["mid", "baron", "support"], counters: ["malphite","shen","ornn","fiora","kayle","cassiopeia","vladimir","kennen","heimerdinger","singed"] },
  poppy: { name: "Poppy", roles: ["baron", "jungle", "support"], counters: ["mordekaiser","darius","gwen","vayne","kayle","fiora","gnar","kennen","teemo","singed"] },
  pyke: { name: "Pyke", roles: ["support"], counters: ["morgana","leona","alistar","braum","thresh","nautilus","soraka","janna","lulu","nami"] },
  rakan: { name: "Rakan", roles: ["support"], counters: ["morgana","janna","soraka","alistar","braum","thresh","zyra","nami","lulu","karma"] },
  rammus: { name: "Rammus", roles: ["jungle"], counters: ["olaf","amumu","shyvana","lillia","graves","lee-sin","vi","warwick","xin-zhao","jarvan-iv"] },
  rell: { name: "Rell", roles: ["support"], counters: ["morgana","janna","soraka","braum","alistar","thresh","zyra","nami","lulu","karma"] },
  renekton: { name: "Renekton", roles: ["baron"], counters: ["vayne","kennen","teemo","jayce","quinn","gnar","kayle","fiora","malphite","darius"] },
  rengar: { name: "Rengar", roles: ["jungle"], counters: ["rammus","lee-sin","amumu","warwick","vi","olaf","xin-zhao","graves","nocturne","jarvan-iv"] },
  riven: { name: "Riven", roles: ["baron"], counters: ["malphite","renekton","sett","poppy","garen","kennen","vayne","teemo","fiora","darius"] },
  rumble: { name: "Rumble", roles: ["baron", "mid"], counters: ["fiora","vayne","gwen","darius","renekton","gnar","kennen","teemo","kayle","jayce"] },
  ryze: { name: "Ryze", roles: ["mid"], counters: ["kassadin","fizz","zed","yasuo","katarina","malphite","irelia","renekton","talon","syndra"] },
  samira: { name: "Samira", roles: ["duo"], counters: ["caitlyn","ashe","jinx","draven","sivir","tristana","miss-fortune","lucian","kai-sa","ezreal"] },
  senna: { name: "Senna", roles: ["support", "duo"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","nami","lulu"] },
  seraphine: { name: "Seraphine", roles: ["support", "mid"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","fizz","zed","yasuo","kassadin"] },
  sett: { name: "Sett", roles: ["baron", "support"], counters: ["vayne","kennen","teemo","jayce","gnar","kayle","fiora","quinn","singed","darius"] },
  shen: { name: "Shen", roles: ["baron", "support"], counters: ["mordekaiser","darius","gwen","vayne","kayle","fiora","gnar","singed","teemo","dr-mundo"] },
  shyvana: { name: "Shyvana", roles: ["jungle", "baron"], counters: ["olaf","lee-sin","graves","kha-zix","vi","xin-zhao","warwick","rengar","rammus","amumu"] },
  singed: { name: "Singed", roles: ["baron"], counters: ["vayne","kennen","teemo","kayle","gnar","jayce","fiora","quinn","gwen","darius"] },
  sion: { name: "Sion", roles: ["baron", "support"], counters: ["fiora","vayne","gwen","mordekaiser","darius","kayle","tryndamere","camille","gnar","kennen"] },
  sivir: { name: "Sivir", roles: ["duo"], counters: ["draven","lucian","samira","kai-sa","vayne","tristana","caitlyn","jinx","ezreal","miss-fortune"] },
  skarner: { name: "Skarner", roles: ["jungle", "baron"], counters: ["olaf","lee-sin","graves","kha-zix","vi","kindred","warwick","xin-zhao","rengar","amumu"] },
  smolder: { name: "Smolder", roles: ["duo", "mid"], counters: ["draven","lucian","samira","kai-sa","tristana","caitlyn","fizz","zed","yasuo","irelia"] },
  sona: { name: "Sona", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","senna","morgana"] },
  soraka: { name: "Soraka", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","senna","morgana"] },
  swain: { name: "Swain", roles: ["support", "mid"], counters: ["fizz","zed","kassadin","yasuo","syndra","orianna","xerath","vel-koz","brand","lux"] },
  syndra: { name: "Syndra", roles: ["mid"], counters: ["fizz","zed","kassadin","yasuo","katarina","malphite","irelia","renekton","diana","akali"] },
  taliyah: { name: "Taliyah", roles: ["mid", "jungle"], counters: ["fizz","zed","kassadin","yasuo","katarina","malphite","irelia","renekton","talon","akali"] },
  talon: { name: "Talon", roles: ["mid", "jungle"], counters: ["malphite","pantheon","renekton","sett","garen","annie","lissandra","mordekaiser","diana","syndra"] },
  teemo: { name: "Teemo", roles: ["baron"], counters: ["irelia","yasuo","camille","fiora","pantheon","akali","jayce","renekton","gnar","yorick"] },
  thresh: { name: "Thresh", roles: ["support"], counters: ["morgana","janna","soraka","braum","alistar","zyra","nami","lulu","karma","senna"] },
  tristana: { name: "Tristana", roles: ["duo", "mid"], counters: ["draven","caitlyn","lucian","sivir","ashe","jinx","miss-fortune","kai-sa","vayne","ezreal"] },
  tryndamere: { name: "Tryndamere", roles: ["baron"], counters: ["malphite","teemo","kennen","vayne","quinn","nasus","jax","fiora","renekton","darius"] },
  "twisted-fate": { name: "Twisted Fate", roles: ["mid"], counters: ["fizz","zed","kassadin","yasuo","katarina","malphite","irelia","renekton","diana","talon"] },
  twitch: { name: "Twitch", roles: ["duo", "jungle"], counters: ["draven","lucian","caitlyn","kai-sa","sivir","tristana","jinx","samira","ashe","ezreal"] },
  urgot: { name: "Urgot", roles: ["baron"], counters: ["fiora","vayne","gwen","mordekaiser","darius","kayle","tryndamere","camille","gnar","kennen"] },
  varus: { name: "Varus", roles: ["duo", "mid"], counters: ["draven","lucian","samira","kai-sa","vayne","tristana","caitlyn","sivir","ezreal","jinx"] },
  vayne: { name: "Vayne", roles: ["duo", "baron"], counters: ["draven","caitlyn","lucian","jinx","tristana","miss-fortune","ashe","kai-sa","sivir","samira"] },
  veigar: { name: "Veigar", roles: ["mid", "support"], counters: ["fizz","zed","kassadin","yasuo","katarina","irelia","diana","akali","talon","xerath"] },
  "vel-koz": { name: "Vel'Koz", roles: ["mid", "support"], counters: ["fizz","zed","kassadin","yasuo","katarina","irelia","diana","akali","talon","ekko"] },
  vex: { name: "Vex", roles: ["mid"], counters: ["syndra","orianna","lux","malphite","ziggs","vel-koz","renekton","brand","viktor","ahri"] },
  vi: { name: "Vi", roles: ["jungle"], counters: ["rammus","lee-sin","olaf","amumu","warwick","graves","xin-zhao","nocturne","jarvan-iv","shyvana"] },
  viego: { name: "Viego", roles: ["jungle"], counters: ["lee-sin","olaf","graves","vi","xin-zhao","warwick","kha-zix","rengar","rammus","amumu"] },
  viktor: { name: "Viktor", roles: ["mid"], counters: ["fizz","zed","kassadin","yasuo","katarina","malphite","irelia","renekton","diana","akali"] },
  vladimir: { name: "Vladimir", roles: ["mid", "baron"], counters: ["malzahar","kassadin","anivia","orianna","syndra","brand","vel-koz","heimerdinger","swain","ryze"] },
  volibear: { name: "Volibear", roles: ["jungle", "baron"], counters: ["vayne","fiora","gwen","kayle","kennen","teemo","singed","olaf","graves","lee-sin"] },
  warwick: { name: "Warwick", roles: ["jungle", "baron"], counters: ["olaf","graves","lee-sin","kha-zix","vi","kindred","xin-zhao","amumu","rammus","rengar"] },
  wukong: { name: "Wukong", roles: ["baron", "jungle"], counters: ["malphite","renekton","darius","garen","sett","fiora","vayne","kennen","teemo","gnar"] },
  xayah: { name: "Xayah", roles: ["duo"], counters: ["draven","lucian","samira","caitlyn","vayne","tristana","sivir","jinx","kai-sa","ezreal"] },
  "xin-zhao": { name: "Xin Zhao", roles: ["jungle"], counters: ["rammus","lee-sin","olaf","amumu","warwick","graves","vi","nocturne","jarvan-iv","kha-zix"] },
  yasuo: { name: "Yasuo", roles: ["mid", "baron"], counters: ["malphite","renekton","pantheon","annie","malzahar","rammus","garen","sett","poppy","akali"] },
  yone: { name: "Yone", roles: ["mid", "baron"], counters: ["malphite","renekton","pantheon","sett","garen","annie","malzahar","akali","irelia","poppy"] },
  yuumi: { name: "Yuumi", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","zyra","brand","senna","soraka"] },
  zed: { name: "Zed", roles: ["mid"], counters: ["malphite","pantheon","sett","renekton","garen","lissandra","malzahar","annie","kayle","galio"] },
  zeri: { name: "Zeri", roles: ["duo"], counters: ["draven","lucian","samira","caitlyn","vayne","tristana","sivir","jinx","kai-sa","ashe"] },
  ziggs: { name: "Ziggs", roles: ["mid", "duo"], counters: ["fizz","zed","kassadin","yasuo","katarina","irelia","diana","akali","talon","ekko"] },
  zilean: { name: "Zilean", roles: ["support", "mid"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","fizz","zed","kassadin","pyke","zyra"] },
  zoe: { name: "Zoe", roles: ["mid"], counters: ["fizz","kassadin","yasuo","zed","katarina","malphite","irelia","renekton","diana","akali"] },
  zyra: { name: "Zyra", roles: ["support"], counters: ["leona","nautilus","thresh","alistar","blitzcrank","pyke","soraka","nami","lulu","janna"] },
};

// Cross-position counter picks: champions flexed from other roles as counters
// key = counter champion, asRole = lane to play the counter in
// Sources: wildriftcounter.com, wr-meta.com, u.gg, community meta knowledge
const CROSS_COUNTERS = {
  // --- Mid lane: baron/jungle/duo champions flexed mid ---
  akali: [
    { key: "sett", asRole: "mid", note: "Sustain + true damage punishes Akali trades" },
    { key: "wukong", asRole: "mid", note: "Clone dodges shroud, strong all-in" },
    { key: "darius", asRole: "mid", note: "Short lane lets Darius zone and all-in" },
  ],
  ahri: [
    { key: "sett", asRole: "mid", note: "Tanks charm, runs her down with W" },
    { key: "irelia", asRole: "mid", note: "Dashes through charm, wins all-ins" },
  ],
  "aurelion-sol": [
    { key: "sett", asRole: "mid", note: "Ignores poke, all-ins easily" },
    { key: "wukong", asRole: "mid", note: "Gap close beats ASol spacing" },
    { key: "irelia", asRole: "mid", note: "Dash-heavy kit disrupts ASol positioning" },
  ],
  brand: [
    { key: "sett", asRole: "mid", note: "Sustain through poke, all-in at 5" },
    { key: "irelia", asRole: "mid", note: "Dashes dodge skillshots, bursts Brand" },
  ],
  corki: [
    { key: "sett", asRole: "mid", note: "Tanks poke, all-ins short range Corki" },
    { key: "irelia", asRole: "mid", note: "Stacks passive off minions, all-ins" },
    { key: "wukong", asRole: "mid", note: "Gap close and burst beats Corki" },
  ],
  diana: [
    { key: "sett", asRole: "mid", note: "True damage and sustain beat Diana trades" },
    { key: "mordekaiser", asRole: "mid", note: "Ult isolates, shield tanks burst" },
  ],
  ekko: [
    { key: "sett", asRole: "mid", note: "Too tanky to burst, punishes Ekko W" },
    { key: "mordekaiser", asRole: "mid", note: "Ult removes Ekko from his ult shadow" },
  ],
  fizz: [
    { key: "sett", asRole: "mid", note: "Survives burst, W true damage kills" },
    { key: "mordekaiser", asRole: "mid", note: "Shield absorbs combo, wins extended trades" },
  ],
  kassadin: [
    { key: "renekton", asRole: "mid", note: "Huge early pressure, denies Kassadin scaling" },
    { key: "sett", asRole: "mid", note: "Early all-in dominance vs weak early Kass" },
    { key: "wukong", asRole: "mid", note: "Strong pre-6 pressure, Kassadin can't trade" },
  ],
  katarina: [
    { key: "sett", asRole: "mid", note: "W stops Katarina ult, too tanky to burst" },
    { key: "mordekaiser", asRole: "mid", note: "Ult isolates, prevents resets" },
    { key: "wukong", asRole: "mid", note: "Clone disrupts combos, strong all-in" },
  ],
  lissandra: [
    { key: "sett", asRole: "mid", note: "Sustain through poke, all-in threat" },
  ],
  lux: [
    { key: "irelia", asRole: "mid", note: "Dashes dodge everything, punishes immobility" },
    { key: "wukong", asRole: "mid", note: "Gap close bypasses Lux range" },
  ],
  orianna: [
    { key: "irelia", asRole: "mid", note: "Dashes make ball placement hard" },
    { key: "wukong", asRole: "mid", note: "All-in beats Orianna spacing" },
    { key: "sett", asRole: "mid", note: "Runs through poke, all-ins" },
  ],
  ryze: [
    { key: "sett", asRole: "mid", note: "Too tanky for Ryze combos, all-ins" },
    { key: "irelia", asRole: "mid", note: "Mobility overwhelms Ryze" },
  ],
  syndra: [
    { key: "irelia", asRole: "mid", note: "Dashes through stun, wins all-in" },
    { key: "wukong", asRole: "mid", note: "Gap close beats Syndra spacing" },
    { key: "sett", asRole: "mid", note: "Sustain through poke, flash+E kills" },
  ],
  "twisted-fate": [
    { key: "irelia", asRole: "mid", note: "Dashes make gold card hard to land" },
    { key: "sett", asRole: "mid", note: "Tanks TF damage, all-ins easily" },
    { key: "wukong", asRole: "mid", note: "Gap close and burst, TF too squishy" },
  ],
  veigar: [
    { key: "irelia", asRole: "mid", note: "Dashes out of cage, all-ins Veigar" },
    { key: "sett", asRole: "mid", note: "Flash+E through cage, too tanky to burst" },
  ],
  "vel-koz": [
    { key: "irelia", asRole: "mid", note: "Dashes dodge skillshots, kills easily" },
    { key: "wukong", asRole: "mid", note: "Gap close destroys immobile Vel" },
    { key: "sett", asRole: "mid", note: "Survives poke, all-ins at close range" },
  ],
  vex: [
    { key: "sett", asRole: "mid", note: "Low mobility champ doesn't proc Vex passive much" },
    { key: "mordekaiser", asRole: "mid", note: "Shield absorbs burst, wins extended fights" },
  ],
  viktor: [
    { key: "irelia", asRole: "mid", note: "Dashes through gravity field, bursts" },
    { key: "sett", asRole: "mid", note: "Runs through poke, all-ins" },
    { key: "wukong", asRole: "mid", note: "Gap close beats Viktor spacing" },
  ],
  yasuo: [
    { key: "rammus", asRole: "mid", note: "Thornmail passive destroys auto-attackers" },
    { key: "wukong", asRole: "mid", note: "Clone baits wind wall, strong all-in" },
    { key: "vi", asRole: "mid", note: "Ult goes through wind wall, armor shred" },
  ],
  yone: [
    { key: "sett", asRole: "mid", note: "W true damage, punishes Yone trades" },
    { key: "rammus", asRole: "mid", note: "Thornmail passive punishes auto-attacks" },
    { key: "wukong", asRole: "mid", note: "Strong all-in, armor stacks" },
  ],
  zed: [
    { key: "rammus", asRole: "mid", note: "Armor stacking, taunt stops combos" },
    { key: "wukong", asRole: "mid", note: "Armor + clone baits Zed ult" },
  ],
  zoe: [
    { key: "irelia", asRole: "mid", note: "Dashes dodge bubbles, all-in kills" },
    { key: "sett", asRole: "mid", note: "Tanks burst, runs Zoe down" },
    { key: "wukong", asRole: "mid", note: "Gap close punishes Zoe immobility" },
  ],
  talon: [
    { key: "rammus", asRole: "mid", note: "Armor stacking, taunt locks Talon down" },
  ],
  // --- Baron lane: duo/mid/jungle champions flexed baron ---
  aatrox: [
    { key: "lucian", asRole: "baron", note: "Ranged poke and dash dodge Aatrox Q" },
  ],
  camille: [
    { key: "lucian", asRole: "baron", note: "Ranged harass, dash escapes hookshot" },
  ],
  darius: [
    { key: "lucian", asRole: "baron", note: "Kites Darius, never lets him stack passive" },
    { key: "tristana", asRole: "baron", note: "Range + jump escapes Darius pull" },
  ],
  "dr-mundo": [
    { key: "lucian", asRole: "baron", note: "Constant poke prevents Mundo healing" },
  ],
  garen: [
    { key: "lucian", asRole: "baron", note: "Kites Garen, denies farm" },
    { key: "tristana", asRole: "baron", note: "Range advantage, jump escapes engage" },
  ],
  gwen: [
    { key: "tristana", asRole: "baron", note: "Range beats Gwen mist, jump escapes" },
  ],
  "k-sante": [
    { key: "lucian", asRole: "baron", note: "Ranged poke, hard to engage on" },
  ],
  mordekaiser: [
    { key: "lucian", asRole: "baron", note: "Kites in death realm, dodges E" },
    { key: "tristana", asRole: "baron", note: "Jump out of E, range advantage" },
  ],
  nasus: [
    { key: "lucian", asRole: "baron", note: "Constant harass prevents stacking" },
    { key: "tristana", asRole: "baron", note: "Zoning + jump prevents Nasus approach" },
  ],
  ornn: [
    { key: "lucian", asRole: "baron", note: "Ranged poke, dodges brittle procs" },
  ],
  renekton: [
    { key: "lucian", asRole: "baron", note: "Kites between dashes, ranged harass" },
  ],
  sett: [
    { key: "lucian", asRole: "baron", note: "Kites Sett, dodges E with dash" },
  ],
  sion: [
    { key: "lucian", asRole: "baron", note: "Constant poke, dash dodges Q" },
    { key: "tristana", asRole: "baron", note: "Range + jump avoids CC chain" },
  ],
  wukong: [
    { key: "lucian", asRole: "baron", note: "Ranged harass before Wukong can engage" },
  ],
  // --- Support: mid/baron champions flexed support ---
  alistar: [
    { key: "brand", asRole: "support", note: "Poke burns through Alistar HP before engage" },
  ],
  leona: [
    { key: "brand", asRole: "support", note: "Punishes Leona for going in with AoE damage" },
    { key: "vel-koz", asRole: "support", note: "Outranges, pokes before engage range" },
  ],
  nautilus: [
    { key: "brand", asRole: "support", note: "Punishes hook engage with burst damage" },
    { key: "vel-koz", asRole: "support", note: "Outranges hook, pokes from safety" },
  ],
  thresh: [
    { key: "brand", asRole: "support", note: "Punishes flay range with poke" },
  ],
};
